chore(deps): bump io.sentry:sentry-android from 7.15.0 to 7.16.0 (#839)
Bumps
[io.sentry:sentry-android](https://github.com/getsentry/sentry-java)
from 7.15.0 to 7.16.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/getsentry/sentry-java/releases">io.sentry:sentry-android's
releases</a>.</em></p>
<blockquote>
<h2>7.16.0</h2>
<h3>Features</h3>
<ul>
<li>Add meta option to attach ANR thread dumps (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3791">#3791</a>)</li>
</ul>
<h3>Fixes</h3>
<ul>
<li>Cache parsed Dsn (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3796">#3796</a>)</li>
<li>fix invalid profiles when the transaction name is empty (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3747">#3747</a>)</li>
<li>Deprecate <code>enableTracing</code> option (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3777">#3777</a>)</li>
<li>Vendor <code>java.util.Random</code> and replace
<code>java.security.SecureRandom</code> usages (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3783">#3783</a>)</li>
<li>Fix potential ANRs due to NDK scope sync (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3754">#3754</a>)</li>
<li>Fix potential ANRs due to NDK System.loadLibrary calls (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3670">#3670</a>)</li>
<li>Fix slow <code>Log</code> calls on app startup (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3793">#3793</a>)</li>
<li>Fix slow Integration name parsing (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3794">#3794</a>)</li>
<li>Session Replay: Reduce startup and capture overhead (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3799">#3799</a>)</li>
<li>Load lazy fields on init in the background (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3803">#3803</a>)</li>
<li>Replace setOf with HashSet.add (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3801">#3801</a>)</li>
</ul>
<h3>Breaking changes</h3>
<ul>
<li>The method
<code>addIntegrationToSdkVersion(Ljava/lang/Class;)V</code> has been
removed from the core (<code>io.sentry:sentry</code>) package. Please
make sure all of the packages (e.g.
<code>io.sentry:sentry-android-core</code>,
<code>io.sentry:sentry-android-fragment</code>,
<code>io.sentry:sentry-okhttp</code> and others) are all aligned and
using the same version to prevent the <code>NoSuchMethodError</code>
exception.</li>
</ul>
<h2>7.16.0-alpha.1</h2>
<h3>Features</h3>
<ul>
<li>Add meta option to attach ANR thread dumps (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3791">#3791</a>)</li>
</ul>
<h3>Fixes</h3>
<ul>
<li>Cache parsed Dsn (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3796">#3796</a>)</li>
<li>fix invalid profiles when the transaction name is empty (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3747">#3747</a>)</li>
<li>Deprecate <code>enableTracing</code> option (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3777">#3777</a>)</li>
<li>Vendor <code>java.util.Random</code> and replace
<code>java.security.SecureRandom</code> usages (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3783">#3783</a>)</li>
<li>Fix potential ANRs due to NDK scope sync (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3754">#3754</a>)</li>
<li>Fix potential ANRs due to NDK System.loadLibrary calls (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3670">#3670</a>)</li>
<li>Fix slow <code>Log</code> calls on app startup (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3793">#3793</a>)</li>
<li>Fix slow Integration name parsing (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3794">#3794</a>)</li>
<li>Session Replay: Reduce startup and capture overhead (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3799">#3799</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/getsentry/sentry-java/blob/main/CHANGELOG.md">io.sentry:sentry-android's
changelog</a>.</em></p>
<blockquote>
<h2>7.16.0</h2>
<h3>Features</h3>
<ul>
<li>Add meta option to attach ANR thread dumps (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3791">#3791</a>)</li>
</ul>
<h3>Fixes</h3>
<ul>
<li>Cache parsed Dsn (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3796">#3796</a>)</li>
<li>fix invalid profiles when the transaction name is empty (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3747">#3747</a>)</li>
<li>Deprecate <code>enableTracing</code> option (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3777">#3777</a>)</li>
<li>Vendor <code>java.util.Random</code> and replace
<code>java.security.SecureRandom</code> usages (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3783">#3783</a>)</li>
<li>Fix potential ANRs due to NDK scope sync (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3754">#3754</a>)</li>
<li>Fix potential ANRs due to NDK System.loadLibrary calls (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3670">#3670</a>)</li>
<li>Fix slow <code>Log</code> calls on app startup (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3793">#3793</a>)</li>
<li>Fix slow Integration name parsing (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3794">#3794</a>)</li>
<li>Session Replay: Reduce startup and capture overhead (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3799">#3799</a>)</li>
<li>Load lazy fields on init in the background (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3803">#3803</a>)</li>
<li>Replace setOf with HashSet.add (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3801">#3801</a>)</li>
</ul>
<h3>Breaking changes</h3>
<ul>
<li>The method
<code>addIntegrationToSdkVersion(Ljava/lang/Class;)V</code> has been
removed from the core (<code>io.sentry:sentry</code>) package. Please
make sure all of the packages (e.g.
<code>io.sentry:sentry-android-core</code>,
<code>io.sentry:sentry-android-fragment</code>,
<code>io.sentry:sentry-okhttp</code> and others) are all aligned and
using the same version to prevent the <code>NoSuchMethodError</code>
exception.</li>
</ul>
<h2>7.16.0-alpha.1</h2>
<h3>Features</h3>
<ul>
<li>Add meta option to attach ANR thread dumps (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3791">#3791</a>)</li>
</ul>
<h3>Fixes</h3>
<ul>
<li>Cache parsed Dsn (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3796">#3796</a>)</li>
<li>fix invalid profiles when the transaction name is empty (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3747">#3747</a>)</li>
<li>Deprecate <code>enableTracing</code> option (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3777">#3777</a>)</li>
<li>Vendor <code>java.util.Random</code> and replace
<code>java.security.SecureRandom</code> usages (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3783">#3783</a>)</li>
<li>Fix potential ANRs due to NDK scope sync (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3754">#3754</a>)</li>
<li>Fix potential ANRs due to NDK System.loadLibrary calls (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3670">#3670</a>)</li>
<li>Fix slow <code>Log</code> calls on app startup (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3793">#3793</a>)</li>
<li>Fix slow Integration name parsing (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3794">#3794</a>)</li>
<li>Session Replay: Reduce startup and capture overhead (<a
href="https://redirect.github.com/getsentry/sentry-java/pull/3799">#3799</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/getsentry/sentry-java/commit/95f6443bdcdb65a2855452a8e6f9fa3bd524d5f7"><code>95f6443</code></a>
release: 7.16.0</li>
<li><a
href="https://github.com/getsentry/sentry-java/commit/285450bbbbbd2f1769481620d5a78abd919bd9a9"><code>285450b</code></a>
Prepare Changelog for 7.16.0 release (<a
href="https://redirect.github.com/getsentry/sentry-java/issues/3816">#3816</a>)</li>
<li><a
href="https://github.com/getsentry/sentry-java/commit/28b6ac91bec6b033b065a308e323020150a2a234"><code>28b6ac9</code></a>
ci(build): Lower gradle workers to max 2 (<a
href="https://redirect.github.com/getsentry/sentry-java/issues/3814">#3814</a>)</li>
<li><a
href="https://github.com/getsentry/sentry-java/commit/4988d5bf9e0a5be708853cf53d07b8503e4c77be"><code>4988d5b</code></a>
test(ui): Add critical tests run by Maestro (<a
href="https://redirect.github.com/getsentry/sentry-java/issues/3802">#3802</a>)</li>
<li><a
href="https://github.com/getsentry/sentry-java/commit/0cc92623d159ad340653a539366b226986e20090"><code>0cc9262</code></a>
[QA] Load lazy fields on init in the background (<a
href="https://redirect.github.com/getsentry/sentry-java/issues/3803">#3803</a>)</li>
<li><a
href="https://github.com/getsentry/sentry-java/commit/0132cddd4dc4f595e45fb47526244ad32cee1c4f"><code>0132cdd</code></a>
[QA] Replace setOf with HashSet.add (<a
href="https://redirect.github.com/getsentry/sentry-java/issues/3801">#3801</a>)</li>
<li><a
href="https://github.com/getsentry/sentry-java/commit/a9b3fbccbea0e319760ce2fa1572c14ad101083e"><code>a9b3fbc</code></a>
Merge branch 'release/7.16.0-alpha.1'</li>
<li><a
href="https://github.com/getsentry/sentry-java/commit/f14a2996d18d2973bdb511c584966b63bb1cf99c"><code>f14a299</code></a>
release: 7.16.0-alpha.1</li>
<li><a
href="https://github.com/getsentry/sentry-java/commit/9182d863db86e7fd645d03ad6d19b441930b1067"><code>9182d86</code></a>
[QA] Cache parsed Dsn (<a
href="https://redirect.github.com/getsentry/sentry-java/issues/3796">#3796</a>)</li>
<li><a
href="https://github.com/getsentry/sentry-java/commit/143f91afb8523188e7319e3324b9d7064ba83a9f"><code>143f91a</code></a>
Bump JamesIves/github-pages-deploy-action from 4.6.4 to 4.6.8 (<a
href="https://redirect.github.com/getsentry/sentry-java/issues/3728">#3728</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/getsentry/sentry-java/compare/7.15.0...7.16.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=io.sentry:sentry-android&package-manager=gradle&previous-version=7.15.0&new-version=7.16.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>