chore(deps): bump org.robolectric:robolectric from 4.11.1 to 4.12.1 (#716)
Bumps
[org.robolectric:robolectric](https://github.com/robolectric/robolectric)
from 4.11.1 to 4.12.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/robolectric/robolectric/releases">org.robolectric:robolectric's
releases</a>.</em></p>
<blockquote>
<p>Robolectric 4.12.1 is a minor release that addressed two issues:</p>
<ol>
<li>Fixed a NoClassDefFoundError when invoking ShadowLog APIs outside of
a Robolectric environment. See <a
href="https://redirect.github.com/robolectric/robolectric/issues/8957">robolectric/robolectric#8957</a>
for details.</li>
<li>Reduced the amount of spurious log noise that may be generated when
attempting to delete temp directories in Windows. See <a
href="https://redirect.github.com/android/nowinandroid/issues/1242">android/nowinandroid#1242</a>
for details.</li>
</ol>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/robolectric/robolectric/compare/robolectric-4.12...robolectric-4.12.1">https://github.com/robolectric/robolectric/compare/robolectric-4.12...robolectric-4.12.1</a></p>
<p>Robolectric 4.12 adds support for the native runtime (native SQLite
and graphics modes) on Windows x86_64. It also contains a large number
of bug fixes and performance improvements.</p>
<p><strong>Note</strong> Robolectric 4.12 uses an updated version of the
<a
href="https://repo.maven.apache.org/maven2/org/robolectric/android-all-instrumented/">preinstrumented
jars</a> (version <code>i6</code>), so if you have infrastructure that
caches or customizes the location of the preinstrumented jars, they will
need to be updated.</p>
<h2>What's Changed</h2>
<ul>
<li>Calling AlwaysOnHotwordDetector constructor reflectively <a
href="https://redirect.github.com/robolectric/robolectric/pull/8549">robolectric/robolectric#8549</a></li>
<li>Bump com.squareup.okhttp3:okhttp-bom from 4.11.0 to 4.12.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8548">robolectric/robolectric#8548</a></li>
<li>Bump androidx.core:core from 1.10.1 to 1.12.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8463">robolectric/robolectric#8463</a></li>
<li>Fix warnings of AndroidSdk.groovy by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8503">robolectric/robolectric#8503</a></li>
<li>Introducing SensorEventBuilder to replace
ShadowSensorManager.createSensorEvent() <a
href="https://redirect.github.com/robolectric/robolectric/pull/8581">robolectric/robolectric#8581</a></li>
<li>Fix LocaleManager.setApplicationLocales(LocaleList) in Android U+ <a
href="https://redirect.github.com/robolectric/robolectric/pull/8583">robolectric/robolectric#8583</a></li>
<li>ShadowDisplayManager: Allowing adding a display with a name. <a
href="https://redirect.github.com/robolectric/robolectric/pull/8591">robolectric/robolectric#8591</a></li>
<li>Bump kotlin from 1.9.10 to 1.9.20 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8594">robolectric/robolectric#8594</a></li>
<li>Bump io.gitlab.arturbosch.detekt:detekt-gradle-plugin from 1.23.1 to
1.23.3 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8595">robolectric/robolectric#8595</a></li>
<li>Bump com.googlecode.libphonenumber:libphonenumber from 8.13.23 to
8.13.24 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8576">robolectric/robolectric#8576</a></li>
<li>Apply Spotless for buildSrc and build script by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8603">robolectric/robolectric#8603</a></li>
<li>Bump api changes checking compatibility version to 4.11.1 by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8606">robolectric/robolectric#8606</a></li>
<li>Bump com.android.tools.build:gradle from 8.1.2 to 8.1.3 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8609">robolectric/robolectric#8609</a></li>
<li>Bump com.ibm.icu:icu4j from 73.2 to 74.1 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8611">robolectric/robolectric#8611</a></li>
<li>Update ShadowNativeSQLiteConnection.nativeOpen to not ignore
parameters <a
href="https://redirect.github.com/robolectric/robolectric/pull/8612">robolectric/robolectric#8612</a></li>
<li>Set the calling activity in ActivityScenario when run in
Robolectric. <a
href="https://redirect.github.com/robolectric/robolectric/pull/8613">robolectric/robolectric#8613</a></li>
<li>Remove duplicated code in ShadowPackageManager.java by <a
href="https://github.com/realdadfish"><code>@​realdadfish</code></a> in
<a
href="https://redirect.github.com/robolectric/robolectric/pull/8614">robolectric/robolectric#8614</a></li>
<li>Improve the fidelity of legacy SQLite error messages by <a
href="https://github.com/hoisie"><code>@​hoisie</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8615">robolectric/robolectric#8615</a></li>
<li>Do not use isFileEncryptedNativeOrEmulated() on Android 14 and later
by <a href="https://github.com/ebiggers"><code>@​ebiggers</code></a> in
<a
href="https://redirect.github.com/robolectric/robolectric/pull/8616">robolectric/robolectric#8616</a></li>
<li>Ignore nativeruntime-dist-compat from Dependabot by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8617">robolectric/robolectric#8617</a></li>
<li>Bump com.android.tools.build:gradle from 8.1.3 to 8.1.4 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8618">robolectric/robolectric#8618</a></li>
<li>Bump androidx-fragment from 1.2.0 to 1.6.2 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8593">robolectric/robolectric#8593</a></li>
<li>Bump org.bouncycastle:bcprov-jdk18on from 1.76 to 1.77 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8619">robolectric/robolectric#8619</a></li>
<li>Switch to use gradle/gradle-build-action@v2.9.0 by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8621">robolectric/robolectric#8621</a></li>
<li>Bump org.jetbrains:annotations from 24.0.1 to 24.1.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8620">robolectric/robolectric#8620</a></li>
<li>Update one GMD config from SDK 33 to 34 by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8622">robolectric/robolectric#8622</a></li>
<li>Ignore androidx annotation auto-update from Dependabot by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8624">robolectric/robolectric#8624</a></li>
<li>Bump com.googlecode.libphonenumber:libphonenumber from 8.13.24 to
8.13.25 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8625">robolectric/robolectric#8625</a></li>
<li>Bump androidx.window:window from 1.1.0 to 1.2.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8626">robolectric/robolectric#8626</a></li>
<li>Don't use isUserKeyUnlocked() after Android 14 by <a
href="https://github.com/ebiggers"><code>@​ebiggers</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8635">robolectric/robolectric#8635</a></li>
<li>Remove JDK requirements statement in README.md by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8636">robolectric/robolectric#8636</a></li>
<li>Enable CodeQL on GitHub Actions by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8607">robolectric/robolectric#8607</a></li>
<li>Use specific version of gradle/gradle-build-action for codeql.yml by
<a href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8638">robolectric/robolectric#8638</a></li>
<li>Bump kotlin from 1.9.20 to 1.9.21 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8644">robolectric/robolectric#8644</a></li>
<li>Bump gradle/gradle-build-action from 2.9.0 to 2.10.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8647">robolectric/robolectric#8647</a></li>
<li>Bump actions/checkout from 3 to 4 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8646">robolectric/robolectric#8646</a></li>
<li>Add ShadowBuild support for missing supported ABI fields by <a
href="https://github.com/jselbo"><code>@​jselbo</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8640">robolectric/robolectric#8640</a></li>
<li>Bump com.googlecode.libphonenumber:libphonenumber from 8.13.25 to
8.13.26 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8645">robolectric/robolectric#8645</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/robolectric/robolectric/commit/46ea4217bd4b7c743a4fc4a489c9003773ed1918"><code>46ea421</code></a>
Bump version to 4.12.1</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/8e9ec0e39c00fb79a6bb467e9542946dbe00c2e2"><code>8e9ec0e</code></a>
Stop logging TempDirectory IOExceptions in Windows</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/85f9641622a7b787c2df750495f03345e0158f2c"><code>85f9641</code></a>
Reduce references to <code>android.util.Log$TerribleFailure</code> in
ShadowLog</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/bb3562e896634615e6bfe64383cff9d89ffa008b"><code>bb3562e</code></a>
Bump version to 4.12.</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/c048ea2e5c547fd5676ac1737dc0a018cb0cc06d"><code>c048ea2</code></a>
Merge branch 'google' into 'master'</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/4421bed8e8e049eded8a0cdb99fb71888bde9d8e"><code>4421bed</code></a>
Bump the preinstrumented jar version to 6</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/cb37bf934a4b1c7b2279eba6606cf51cafef636d"><code>cb37bf9</code></a>
Remove several shadow methods in ShadowViewConfiguration</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/8ba90c1fe96c108c4b9077f5b280c2aa9faad4f3"><code>8ba90c1</code></a>
Remove BuckManifestFactory</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/a8889115c3a5ec999588ba271f4199def3a6430a"><code>a888911</code></a>
Fix issue with publishing preinstrumented jars</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/c386cfa106dfb067cb24cb81bd4edef0bad3f24e"><code>c386cfa</code></a>
Merge branch 'master' into 'google'</li>
<li>Additional commits viewable in <a
href="https://github.com/robolectric/robolectric/compare/robolectric-4.11.1...robolectric-4.12.1">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.robolectric:robolectric&package-manager=gradle&previous-version=4.11.1&new-version=4.12.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>